// Version de la app (cargado antes de index.html inline script)
window.APP_VERSION = {
  version: '1.5.8',
  date: '2026-04-16',
  changes: [
    'Calendario ahora muestra horas de inicio y fin de los eventos',
    'Limpiados logs de depuración del Calendar API y spreadsheet',
    'Sincronización Calendar -> Sheets ahora guarda hora inicio y fin (columnas M y N)',
    'Sesiones en Sheets ahora guardan hora inicio y fin (columnas M y N)',
    'Proxy de Calendar corregido: list usa GET (evita error "Missing end time")',
    'Calendario optimizado para móviles - texto más grande y legible',
    'Eventos del calendario ahora más grandes en dispositivos móviles',
    'Espaciado mejorado entre elementos del calendario en móvil',
    'Fix: Eventos sin horas ahora se muestran como eventos de día completo en FullCalendar',
    'Mejor validación de horas vacías para evitar mostrar 00:00 incorrectamente',
    'Logs de depuración añadidos para identificar problemas con horas en FullCalendar',
    'Botones del toolbar del calendario más grandes en táctil',
    'Altura mínima de celdas aumentada para mejor usabilidad',
    'Fix: Problema de timezone en FullCalendar - ahora muestra horas locales correctas',
    'Corregida conversión UTC que mostraba 1-2 horas menos en eventos',
    'Fix: Formato de tiempo en FullCalendar - ahora muestra HH:mm completo',
    'Mejor visualización de horas en PC con configuración optimizada',
    'Personalización de títulos por dispositivo: PC muestra grupo+horas, móvil solo grupo',
    'Eliminados logs de depuración del calendario para producción',
    'Búsqueda de direcciones solucionado - mapa ahora se mueve al marcador',
    'map.setCenter() añadido a searchOnMap para centrar mapa en resultados',
    'Experiencia de usuario mejorada al buscar direcciones',
    'Mapa ahora se centra automáticamente en ubicaciones encontradas',
    'Error AdvancedMarkerElement - mapa sin ID válido solucionado',
    'Map ID configurado correctamente para AdvancedMarkerElement',
    'mapId: PERCU_MANAGER_MAP asignado al mapa',
    'ID de contenedor map-container actualizado',
    'AdvancedMarkerElement ahora funciona sin errores',
    'Migración completa a AdvancedMarkerElement (google.maps.Marker deprecated)',
    'API moderna de Google Maps implementada con fallback robusto',
    'Warning de deprecated eliminado completamente',
    'Manejo de permisos de geolocalización denegados mejorado',
    'Mensajes informativos para permisos bloqueados por usuario',
    'Geolocalización con fallback elegante y UX mejorada',
    'Error loading is not defined al usar ubicación actual solucionado',
    'Variable loading correctamente obtenida del DOM en openMapModal',
    'Ubicación actual ahora funciona sin errores',
    'Error initializeMap is not defined al abrir mapa solucionado',
    'Función initializeMap creada para mapa interactivo',
    'Mapa interactivo ahora funciona correctamente',
    'Error 500 persistente en proxy api/maps solucionado definitivamente',
    'Proxy simplificado para usar callback simple (initMap)',
    'Eliminado problema de callback codificado complejo',
    'Google Maps API ahora carga sin errores 500',
    'Error 500 en proxy api/maps con callback codificado solucionado',
    'Callback URL-decodificado correctamente en proxy',
    'SyntaxError en callback de Google Maps solucionado',
    'Proxy api/maps.js revertido a redirección con CORS',
    'Error de sintaxis en JavaScript de Google Maps corregido',
    'CORS entre GitHub Pages y Vercel solucionado',
    'Endpoint api/maps.js actualizado con headers CORS',
    'Google Places Autocomplete solucionado (importLibrary + fallback)',
    'Error google.maps.places.Autocomplete undefined corregido',
    'Manejador global de errores asíncronos implementado',
    'Google Maps async loading solucionado (método importLibrary)',
    'Eliminado warning de performance de Google Maps',
    'Carga asíncrona optimizada según best practices',
    'Error 404 CSS solucionado para GitHub Pages',
    'CSS compilado movido a raíz (styles.css)',
    'HTML actualizado para usar CSS accesible',
    'Tailwind CSS compilado para producción (sin CDN)',
    'Node.js v24.14.1 detectado y configurado',
    'CSS optimizado de 17KB minificado',
    'Sistema de build automatizado implementado',
    'Popup de error moderno y bonito para reemplazar alerts',
    'Diseño con iconos dinámicos según tipo (error, warning, info, success)',
    'Focus automático en campo con error',
    'Reemplazo completo de alerts del sistema',
    'Columna H siempre con valor 1 independientemente de duración real',
    'Validación completa de campos obligatorios en formulario de clase',
    'Validación de hora fin posterior a hora inicio',
    'Duración por defecto de 1 hora al abrir popup',
    'Limpieza automática del formulario al reabrir',
    'Corregido proxy calendar.delete para manejar 204 No Content',
    'Corregido guardado de Calendar Event ID en nuevas sesiones',
    'Limpiado logging detallado de actualizarRealizados',
    'Corregida lógica para procesar TODAS las filas del spreadsheet',
    'Corregido proxy sheets.update (método PUT)',
    'Sistema de control de versiones añadido'
  ]
};

